### PR TITLE
Towards stuttgart 2.0

### PR DESCRIPTION
**Pull request by Janekdererste**
This is a draft PR, so that @davidwedekind can review the removal of pt-extensions and everything that relies on this. 

The pt-extension did not update its dependency and can't be build in its current state. I don't need it, but I need to move foreward with the model. Therefore, I removed everything which caused problems. @davidwedekind do you want to have the removed components i.e. src/main/java/org/matsim/stuttgart/run/StuttgartMasterThesisRunner.java and others in the project?

### CODE REVIEW

**Comment by vsp-gleich** [comment]
Someone could have let me known, I updated pt-extensions (commit c6cd2aa65b84dac8d94457505a55b8d74eeeeaf2). For me it never failed probably because there is a version ready built on my local machine and maven never builds anything new.

**Comment by Janekdererste** [comment]
Sorry @vsp-gleich, I just discovered this yesterday and needed to do something. Will you update the pt-extensions, so that the build succeeds again? Then I can leave this in. Still, I'm not sure whether this belongs into this scenario or whether this belongs into @davidwedekind 's master thesis?

**Comment by vsp-gleich** [comment]
I updated it yesterday and it was built successfully on github actions (https://github.com/matsim-vsp/pt-extensions/runs/3003056712). I checked out matsim-stuttgart and switched the version to that most recent commit (this is how jitpack dependencies need it to update) and jitpack did built successfully (https://jitpack.io/#matsim-vsp/pt-extensions/c6cd2aa65b). Now the maven update in IntelliJ for matsim-stuttgart did fail despite that giving lots of other dependencies missing. I don't know

**Comment by Janekdererste** [comment]
Thanks @vsp-gleich 🙏

**Comment by vsp-gleich** [comment]
I opened a pull request which updates the pt-extensions version #33 . It shows no build or test, so I cannot confirm it works. On my local machine IntelliJ gives lots of missing dependencies, some of them definitely not related to pt-extensions (referencing matsim-14-PR1516 when I updated pt-extensions to matsim-14-PR1583). Probably some stupid IntelliJ issue I have no time to debug now. Maybe it's best if you check if it works for you.

**Comment by Janekdererste** [comment]
That's more than enough. Thanks again.

**Pull request merged**
